### ISSUE TITLE
Reusable Blocks Error

### ISSUE THREAD

**Issue by benjaminluoma** [godaddy/coblocks#560]
So... I'm suddenly getting an error message when I try to use any reusable blocks. This happens whether or not there is a coblocks block in the reusable block or not.

TypeError: Cannot read property 'attributes' of null
    at http://lszoo.test/wp-content/plugins/coblocks/dist/blocks.build.js?ver=1559162342:1:361290
    at Td (http://lszoo.test/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:82:11)
    at hi (http://lszoo.test/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:102:385)
    at Qg (http://lszoo.test/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:144:217)
    at Rg (http://lszoo.test/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:145:76)
    at Sc (http://lszoo.test/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:158:109)
    at Z (http://lszoo.test/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:156:492)
    at Kc (http://lszoo.test/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:155:52)
    at si (http://lszoo.test/wp-content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:132:65)
    at Q (http://lszoo.test/wp-content/plugins/gutenberg/vendor/react.min.f4c1469c.js:11:262)

**Comment by richtabor** [comment]
Hey @benjaminluoma are you using the Gutenberg plugin? If so, what version are you using? If not, what version of WordPress are you running?

**Comment by benjaminluoma** [comment]
Thanks for the quick response Rich. So... yes I am using the Gutenberg plugin. Version 5.8.0. Latest version of WP. Here's all my active plugins:

![image](https://user-images.githubusercontent.com/2529580/58592986-67ea6880-822f-11e9-9b87-2e044da5536f.png)

I can say that all was running fine and dandy until I activated woocommerce - probably a red herring.

**Comment by richtabor** [comment]
Thanks @benjaminluoma! I actually think I've tackled this issue this afternoon. 

I have a PR #559 if you'd want to give that a shot and let me know if that works for you. If you're unfamiliar with the workings of GitHub I can send you a zip.

**Comment by benjaminluoma** [comment]
@richtabor huzzah! That worked dude ;-)

You = the man.

**Comment by richtabor** [comment]
Good to hear @benjaminluoma!
